function cfg = pipeline_config()
% PIPELINE_CONFIG  처리·그림 생성 단계가 공유하는 단일 설정 파일.
% 새 데이터를 추가할 때는 cfg.targets와 (그림이 필요하면) cfg.figureTargets를 수정한다.

cfg.rootDir = fileparts(fileparts(fileparts(mfilename('fullpath'))));

cfg.sensorNames = {'Avanti Sensor 1', 'Avanti Sensor 2', 'Mini Sensor 5', 'Mini Sensor 6', ...
                   'Avanti Sensor 3', 'Avanti Sensor 4', 'Mini Sensor 7', 'Mini Sensor 8'};
cfg.muscleNames = {'L_TA', 'L_GM', 'L_RF', 'L_VL', 'R_TA', 'R_GM', 'R_RF', 'R_VL'};
cfg.sideNames = struct('L', 'Left', 'R', 'Right');
cfg.muscleFullNames = struct('TA', 'TibAnt', 'GM', 'Gastroc', ...
    'RF', 'RectFem', 'VL', 'VastLat');

cfg.trials = struct( ...
    'key',        {'bare', 'p1', 'p2', 'p3'}, ...
    'emgFile',    {'bare.csv', 'P1.csv', 'P2.csv', 'P3.csv'}, ...
    'bagFile',    {'bare.bag', 'p1.bag', 'p2.bag', 'p3.bag'}, ...
    'gaitSuffix', {'BARE', 'p1', 'p2', 'p3'}, ...
    'label',      {'bare', 'P1', 'P2', 'P3'});

% process 단계에서 사용할 subject/date. enabled=false로 바꾸면 해당 항목은 건너뛴다.
cfg.targets = struct( ...
    'subject', {'SAH01', 'SAH01', 'SAH03', 'SAH03', 'SAH04', 'SAH04', 'SAH04'}, ...
    'dateStr', {'260706', '260713', '260623', '260630', '260728', '260804', '260811'}, ...
    'gaitPct', {[0, 70, 100], [0, 70, 100], [-10, 60, 90], [-10, 60, 90], ...
                [-10, 60, 90], [-10, 60, 90], [-10, 60, 90]}, ...
    'enabled', {true, true, true, true, true, true, true});

% 검증된 step 범위가 있는 날짜만 figureTargets에 둔다.
cfg.figureTargets = struct('subject', {}, 'dateStr', {}, 'affectedSide', {}, 'stepRange', {});
cfg.figureTargets(1) = makeFigureTarget('SAH01', '260706', 'L', 3:73, 18:88, 7:77, 5:75);
cfg.figureTargets(2) = makeFigureTarget('SAH01', '260713', 'L', 3:73, 4:74, 8:78, 3:73);
cfg.figureTargets(3) = makeFigureTarget('SAH03', '260623', 'L', 4:74, 51:121, 3:73, 23:93);
cfg.figureTargets(4) = makeFigureTarget('SAH03', '260630', 'L', 4:74, 14:84, 15:85, 15:85);

% 필요한 그림만 true로 바꾼다. angle 그림은 emg_afo_steps가 있어야 한다.
cfg.figureOptions = struct( ...
    'rmsBar', false, ...
    'gaitProfile', false, ...
    'rawEMGStep', false, ...
    'peakTiming', false, ...
    'rawEMGAll', false, ...
    'validPeakTable', false, ...
    'fatigueTrend', false, ...
    'rawEMGWithAngle', true, ...
    'profileWithAngle', true, ...
    'lpfCutoffHz', 8, ...
    'profileStd', true, ...
    'validPeakDelta', 0.5);
end

function target = makeFigureTarget(subject, dateStr, affectedSide, bare, p1, p2, p3)
target.subject = subject;
target.dateStr = dateStr;
target.affectedSide = affectedSide;
target.stepRange = struct('bare', bare, 'P1', p1, 'P2', p2, 'P3', p3);
end
